### ISSUE TITLE
Need example using loopback-component-passport

### ISSUE THREAD

**Issue by JonnyBGod** [strongloop/loopback-component-oauth2#14]
I have been trying to implement this component with the previously working login setup I had using component-passport.

At the moment I am stuck with the routes. I mean, when I protect '/api' with oauth2 all api routes become authenticated only which mean routes like '/api/users/login' or POST '/api/users' will return 401 Unauthorized.

A full example is much needed.

**Comment by raymondfeng** [comment]
Have you checked out https://github.com/strongloop/loopback-gateway?

**Comment by JonnyBGod** [comment]
I did and the jwt authentications works fine. The problem is when trying to support google, facebook or even the angularjs User.login() flow is broken.

**Comment by loay** [comment]
Hi @JonnyBGod 
Here is a full example: https://github.com/strongloop/loopback-example-passport
Please let me know if you have any questions. Regards,
