### ISSUE TITLE
How setup crossdomain allow in exchange/clientCredentials.js

### ISSUE THREAD

**Issue by zetflo** [strongloop/loopback-component-oauth2#17]
Hello,

I need to activate cross domain at the token retrieval request ( /oauth/token ) . 
Currently the CORS is managed side loopback rest but not in the loopback file component-OAuth2/lib/exchange/clientCredentials.js .

How to configure the CORS for this query ?

**Comment by raymondfeng** [comment]
You can enable CORS by adding the `cors` middleware (https://github.com/troygoode/node-cors). Feel free to submit a PR so that we enable it by default.

**Comment by zetflo** [comment]
Great, it's work perfectly.

Thanks for your reply.
