### ISSUE TITLE
Unable to identify when login is failed

### ISSUE THREAD

**Issue by wascou** [strongloop/loopback-component-oauth2#21]
Hi,

When the component must ensure that the user is logged, depending on the grant method, we generally reach the following line of code inside `oauth2-loopback.js` : 

```
login.ensureLoggedIn({ redirectTo: options.loginPage || '/login' }),
```

If we send back false as user, the component redirect the user to exactly the same _loginPage_ and there's no way to indicate to the user that he does not give the right login/password.

May you make this configurable so we can set a GET param to indicate that the login did not go well ?

Cheers.

Max

**Comment by wascou** [comment]
I hacked the redirection for implicit protocol so I can detect in the site.js that something went wrong and show a different template for example :
I replace [this](https://github.com/strongloop/loopback-component-oauth2/blob/v2.2.0/lib/oauth2-loopback.js#L822) by this :
````
failureRedirect: options.loginPage + '?loginFailed' || '/login'
````

**Comment by richardpringle** [comment]
@wascou, I know this is pretty old, but any chance you want to create a PR so you get the credit?
