### ISSUE TITLE
Missing the revoke endpoint

### ISSUE THREAD

**Issue by XinV** [strongloop/loopback-component-oauth2#25]
The OAuth2 spec has revoke endpoint:
POST /revoke HTTP/1.1
Host: server.example.com
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

token=45ghiukldjahdnhzdauz&token_type_hint=refresh_token

Can loopback-component-oauth2 provides this endpoint soon so that we can build the open api platform on top of loopback-component-oauth2 easily? Thanks.

**Comment by raymondfeng** [comment]
Where do you see the `revoke` endpoint in the oAuth 2.0 spec - https://tools.ietf.org/html/rfc6749? I couldn't find it.

**Comment by XinV** [comment]
ah, i saw it here: https://tools.ietf.org/html/rfc7009

**Comment by raymondfeng** [comment]
I just implemented and released the feature in 2.0.0-rc2.

**Comment by XinV** [comment]
Very cool. Thanks
