### ISSUE TITLE
OAuthScope createModel issue

### ISSUE THREAD

**Issue by woodedlawn** [strongloop/loopback-component-oauth2#30]
I've been running into problems creating instances of OAuthScope, and I noticed that in oauth2-models.js, the getSettings function is applied to each model definition to return an options object before creating the model, except for when creating the OAuthScope model.

https://github.com/strongloop/loopback-component-oauth2/blob/master/lib/models/oauth2-models.js#L51-L55

When I use the getSettings function on scopeDef before passing it into the createModel method, my problems go away...

**Comment by raymondfeng** [comment]
Patch pls?

**Comment by richardpringle** [comment]
Looks like the patch has been landed so I will close this issue. Please re-open the issue and mention me in a comment if the issue persists!
