### ISSUE TITLE
"error_description": "ER_NO_SUCH_TABLE: Table 'db_test.OAuthClientApplication' doesn't exist"

### ISSUE THREAD

**Issue by UVk** [strongloop/loopback-component-oauth2#52]
Was trying to implement loopback-component-oauth2 so my server will be an OAuth provider. I'm using 
MySQL on AWS (RDS service) as a data source (Node 6.9.1, Loopback 2.29.1).
It seems that the implementation does not create the needed tables reflected in the model.
Using Postman as client I'm getting the above error.

**Comment by maziarz** [comment]
I have the same error. Does not generate the tables either.

`"error_description": "relation \"public.oauthclientapplication\" does not exist"`

**Comment by ThisIsMarkSantiago** [comment]
I get the same error when I set the datasource to mysql.
But not when using db(memory)
