### ISSUE TITLE
How do I connect OAuthAccessToken model & the AccessToken model?

### ISSUE THREAD

**Issue by talpasco** [strongloop/loopback-component-oauth2#53]
I'm trying to set myself as a provider.

Decision step is working flawlessly.
User is logging-in,
and is getting a token & a refresh token.

I'm failing to understand how this is connected to the AccessToken model.
When is the connection between the OAuthAccessToken model & the AccessToken model suppose to happen?
What am I missing? How does the user supposed to get his accessToken, so he would have access to our API?

Thanks,
Tal
BTW, you guys at loopback rocks!!!

**Comment by asgpha** [comment]
On the resource application,

1. created a model call OAuthToken that extends to AccessToken

2. add the following code in app.start

`app.use(loopback.token({
    model: app.models.OAuthToken,
  }));`

**Comment by UVk** [comment]
This issue is important and should not be stale.

**Comment by deviant32** [comment]
+1
