### ISSUE TITLE
Flash Errors

### ISSUE THREAD

**Issue by talpasco** [strongloop/loopback-component-oauth2#63]
Hi,

Couldn't flash the error message after a failed login attempt.
And then I realized that the strategy is being set 'hard-coded' ('loopback-component-oauth2\lib\oauth2-loopback.js', line 828).

And so, I modified it to use the 'local' strategy, and to flash errors... and voila, it works.
This is how:
`app.post(options.loginPath || '/login',
      passport.authenticate('local',
      {successReturnToOrRedirect: '/',
        failureRedirect: options.loginPage || '/login',
        failureFlash: true}));`

I was wondering if there is a way to configure it, outside of the node-module scope.

Thanks,
Tal

**Comment by UVk** [comment]
This issue is important and should not be stale.
