### ISSUE TITLE
Protect only certain remote methods of a particular endpoint.

### ISSUE THREAD

**Issue by vaideesh07** [strongloop/loopback-component-oauth2#64]
- [ ] Feature request

I want to protect my /v1/Users endpoint using loopback-component-oauth2 but I want to have the create method (i.e. the POST /v1/Users) to be open and allow unauthenticated requests. I am not able to achieve this. I am able to either protect all endpoints or protect none . The User model in my application extends the default User model of loopback. How do I overcome this ?

**Comment by Caiuse** [comment]
I want to achieve the same thing but with the email /User/confirm endpoint. Is this possible?
