### ISSUE TITLE
Passport serializeUser/deserializeUser never be called

### ISSUE THREAD

**Issue by dongmai** [strongloop/loopback-component-oauth2#67]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

I'm trying to use the component but I couldn't get it working, after looking through source code and debugging I found that the two methods of passport never be called. I've also tried with the example of oauth2orize at [https://github.com/gerges-beshay/oauth2orize-examples](url), it then totally worked. 

And because they aren't worked so any further requests are considered as **unauthorized request**

### Link to sample repo to reproduce issue (if bug)

This is my server.js
<img width="478" alt="screen shot 2017-06-02 at 11 05 34 am" src="https://cloud.githubusercontent.com/assets/3855966/26710364/75829956-4783-11e7-984f-77a34023eaa7.png">

What I've done to find the issue:
- Run app with: DEBUG="loopback:oauth2"
- Login with username/password via POST http://0.0.0.0:3000/login successfully 
- Check logs but didn't see any info about the two functions to notice it worked: 
<img width="491" alt="screen shot 2017-06-02 at 11 06 21 am" src="https://cloud.githubusercontent.com/assets/3855966/26710373/87c6f65c-4783-11e7-9245-6f938fa49664.png">

(Sorry I dont have a repo for it)

### Additional information (Node.js version, LoopBack version, etc)
This is my package.json: 
<img width="609" alt="screen shot 2017-06-02 at 11 06 50 am" src="https://cloud.githubusercontent.com/assets/3855966/26710383/99b3aba8-4783-11e7-956a-d8ef92d8b501.png">

Can please someone have a look at this and suggest me any solution? Many thanks :)

**Comment by dongmai** [comment]
I've resolved this by changing the way to use express session middleware (in server.js) as:
`app.middleware('session', session({ secret: 'keyboard cat' }));`

Through some topics on stackoverflow I see that need to use the middleware before two middlewares of passport `initialize` and `session`, and as in the component's source code those are used at **auth** phase

<img width="419" alt="screen shot 2017-06-02 at 2 02 51 pm" src="https://cloud.githubusercontent.com/assets/3855966/26714563/2ef7bc1e-479c-11e7-854f-18f958d79911.png">

So I need to use express session middleware at **session** phase.

Just post here for someone facing this like me.

**Comment by J-Kazama** [comment]
I was getting a middleware error and serializer was not working for me as well.

After putting:
```
app.use(passport.initialize());
app.use(passport.session());
```
before any other app.use, the issue was resolved.
